# Extensions Troubleshooting Document: https://community.appdynamics.com/t5/Knowledge-Base/How-to-troubleshoot-missing-custom-metrics-or-extensions-metrics/ta-p/28695

# Please refer to step 4 in the Extensions Troubleshooting Document for instructions on how to obtain your Tier ID
# Please make sure your metric prefix always ends with a '|'
metricPrefix: "Server|Component:<Tier ID/Tier Name>|Custom Metrics|Netscaler Monitor|"

# Configure your Netscaler ADX servers here
servers:
 - name: ""
   host: ""
   port: ""
   username: ""
   password: ""
   encryptedPassword: ""

#Please refer to the Password Encryption Documentation for instructions on how to configure an encryptionKey & encryptedPassword
# https://community.appdynamics.com/t5/Knowledge-Base/How-to-use-Password-Encryption-with-Extensions/ta-p/29397
encryptionKey:

numberOfThreads: 20

# The metrics published by the extension. You can configure additional metrics using the Netscaler API documentation
# https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/11.1/statistics/statistics/?_ga=2.173931875.1514738593.1519078996-904321061.1516686644
metrics:
 Service:
   - throughput:
       alias: "throughput" #Throughput in mbps
   - avgsvrttfb:
       alias: "avgsvrttfb" #Average time to first byte
   - totalrequests:
       alias: "totalrequests" #Total number of requests received on the service
   - totalresponses:
       alias: "totalresponses" #Total number of responses
   - curclntconnections:
       alias: "curclntconnections" #Number of connections to the client
   - cursrvrconnections:
       alias: "cursrvrconnections" #Number of connections to the server
   - activetransactions:
       alias: "activetransactions" #Number of active transactions handled by the service
   - state:
       alias: "state" #Current state of the system
       convert:
         "DOWN" : 0
         "UP" : 1
         "UNKNOWN" : 2
         "OFS" : 3 #Out of service
         "TROFS" : 4 #Transition out of service"
         "TROFS_DOWN" : 5 #Down when going out of service

 System:
   - cpuusagepcnt:
       alias: "cpuusagepcnt" #CPU utilization in %
   - memsizemb:
       alias: "memsizemb" #Currently allocated memory in MB
   - memusagepcnt:
       alias: "memusagepcnt" #Percentage of memory utilization

 Load Balancing:
   - tothits:
       alias: "tothits" #Total number of hits
   - totalrequests:
       alias: "totalrequests" #Total number of requests
   - totalresponses:
       alias: "totalresponses"  #Total number of responses
   - cursrvrconnections:
       alias: "cursrvrconnections" #Number of connections to the server behind the virtual server
   - curclntconnections:
       alias: "curclntconnections" #Number of client connections
   - state:
       alias: #Current state of the system
       convert:
         "DOWN" : 0
         "UP" : 1
         "UNKNOWN" : 2
         "OFS" : 3 #Out of service
         "TROFS" : 4 #Transition out of service"
         "TROFS_DOWN" : 5 #Down when going out of service
